### ISSUE TITLE
[BUG] Missing functionality - Regions

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#221]
**Describe the bug**
There is a functionality for adding / managing regions which is missing in Primate UI.

**To Reproduce**
1. Look at the main menu on the left - there's no functionality for adding / managing regions.

**Expected behavior**
There must be a functionality to add / edit / remove regions.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76606790-936ae500-651b-11ea-9901-19e69dd9977d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by rhtyd** [comment]
Not supported feature, in fact since this is a unfinished feature we may decide to not even show in Primate cc @PaulAngus ?
Please close for now as it's out of scope of tech preview and documented under list of things to do after tech preview here https://github.com/apache/cloudstack-primate/projects

**Comment by vladimirpetrov** [comment]
I agree, if it's not supported, it doesn't make sense to show it in the UI. Closing the issue.
