### ISSUE TITLE
[BUG] Identify and Access > Accounts > New account - 'Domain' and 'Role' must be mandatory fields

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#238]
**Describe the bug**
It's not possible to create account without entering 'Domain' and 'Role' so they must be mandatory, as in the old UI.

**To Reproduce**
1. Go to 'Identify and Access > Accounts' and click on 'Add account'. 

**Expected behavior**
'Domain' and 'Role' fields must be mandatory, as in the old UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/76977725-5c8f3780-693e-11ea-923b-55a988d9f618.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

**Comment by shwstppr** [comment]
@rhtyd @utchoang any other solution for this than adding custom form

**Comment by rhtyd** [comment]
Could be related:
https://github.com/apache/cloudstack-primate/pull/170
https://github.com/apache/cloudstack-primate/pull/217

**Comment by shwstppr** [comment]
@rhtyd This is because both these parameters are not a required parameter in createAccount API
https://github.com/apache/cloudstack/blob/master/api/src/main/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java#L63-L67
Either we change backend or use a custom form. PR already created #257

**Comment by rhtyd** [comment]
Have PR
