### ISSUE TITLE
Add missing B&R features

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#253]
Add the following missing UI features wrt B&R:

- Add offering support that imports external offering
- Support for backup user-defined schedule
- Restore volume and attach it to a VM from a backup

Screenshots:

![Screenshot from 2020-03-25 17-21-03](https://user-images.githubusercontent.com/95203/77533566-1fd2bb80-6ebd-11ea-8f1f-9bd6c58f1d40.png)
![Screenshot from 2020-03-25 17-21-19](https://user-images.githubusercontent.com/95203/77533570-2103e880-6ebd-11ea-9051-4bf5dd9307e0.png)
![Screenshot from 2020-03-25 17-21-30](https://user-images.githubusercontent.com/95203/77533574-219c7f00-6ebd-11ea-8d99-3dbc5493849a.png)

**Comment by rhtyd** [comment]
@utchoang cc @svenvogel since you'd done the snapshot schedule feature, can you pick this up - see http://primate-qa.cloudstack.cloud:8080/client/ for example of a backup schedule on the 'AdminFirstVM' VM. If possible can you prioritise this over your NSP support work? Thanks.

**Comment by utchoang** [comment]
Hi @rhtyd , I can't connect to http://primate-qa.cloudstack.cloud:8080/client/ because when login I have gotten the message: "Invalid username or password.
This could also be a restriction on the IP address you are connecting from."
Although I have an input username / password correct.
![image](https://user-images.githubusercontent.com/13766648/77728330-defab400-702e-11ea-86d1-4ab703db8768.png)

**Comment by rhtyd** [comment]
Hi @utchoang can you try again, there was an issue at mysql/mgmt server that has been temporarily fixed.

**Comment by rhtyd** [comment]
Tested, LGTM.
