### ISSUE TITLE
[BUG] Missing side info scroller in the 'New instance' dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#263]
**Describe the bug**
In the 'New instance' dialog there is an instance info section that fills the instance data on the fly - as they are entered. There is no way to see it all though - no scroller is present.

**To Reproduce**
1. Go to 'Compute > Instances' and click on the 'Add instance' icon. 
2. Enter the required parameters in the dialog, then look on the right - the instance data is added as you enter them but there is no scroller so you cannot see all of the information.

**Expected behavior**
There must be a scroller on the instance info section because it's longer than the screen height.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/77737992-b3b89a80-7017-11ea-9621-c4f315726dd6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
None.

**Comment by shwstppr** [comment]
@rhtyd since we have used `Affix` element as a parent for info card here we can't have it scrolling down. Design change here?
Maybe fixing height of info card to something like 75% of parent and then use scroll if needed? Though I'm sure about its implementation

**Comment by rhtyd** [comment]
@shwstppr we could try to put in a scrollbar inside the affix element, using veritcal scroll like `  overflow-y: scroll;` ?

**Comment by shwstppr** [comment]
@rhtyd I don't think I'm best placed to address purely UI issues

**Comment by rhtyd** [comment]
I'm not sure how to fix that, because that's an affix component. I tried add a scroll bar which did not work.
@svenvogel @utchoang can you think of something to fix the instance summary on right side? Maybe only display limited options (but not all) such as name, ostype, cpu, ram, disk, template, SSH key and zone. Things such as compute, network, disk offerings and networks (because they could be any number) could be hidden. Alternatively, add a scrollbar option?
For reference this is how it looks in the old UI:
![Screenshot from 2020-06-04 13-38-44](https://user-images.githubusercontent.com/95203/83731863-d5ae4900-a668-11ea-8724-235ac5460728.png)

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I tried adding scroll with CSS, and it goes like this. What do you think about this?
![image](https://user-images.githubusercontent.com/13766648/83846007-1aeb7d00-a734-11ea-8d29-8e55f0fc694d.png)
