### ISSUE TITLE
Misc List Views

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#3]
Misc/low priority:

**Comment by ggoodrich-ipp** [comment]
I have been investigating the sorting mechanism built into ant-design-vue in hopes of fulfilling the sort-key feature listed in the description. I've extracted some of the code leveraged by the old UI for sorting, in order to hopefully set the Table.sorter to call this new function. However, what I've discovered is that I can find no mechanism with which to determine which column is being clicked/sorted. The mechanism only passes (a, b, sortOrder), with a and b seeming to be Vue.js data objects that contain, essentially, the data for an entire row in the table. I've found a spot in the ant-design-vue code where I can pass another parameter - sortColumn as the fourth parameter, and this solves the problem. I've been testing it locally. If no-one knows of another good way to accomplish this, I will issue a PR against ant-design-vue to get this change incorporated.

The referenced line would be changed to be:
`const result = sortColumn.sorter(a, b, sortOrder, sortColumn);`

Here is a [link to the current line](https://github.com/vueComponent/ant-design-vue/blob/46644ff435359c6a5c707444b3828bcb99258a74/components/table/Table.jsx#L351) within the ant-design-vue repo

**Comment by rhtyd** [comment]
@ggoodrich-ipp column specific sorting function are defined in the auto-generated view/generator component like this: https://github.com/apache/cloudstack-primate/blob/master/src/views/AutogenView.vue#L344 (this is a very basic method, probably won't work for anything other than strings)

**Comment by rhtyd** [comment]
Split and moved to other tickets.
