### ISSUE TITLE
[BUG] Change order of Service offering is available to Read-only admin 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#457]
**Describe the bug**
With the latest default role introduced - read only admin he's able to see the buttons for changing the order of * offerings
When click on some of the buttons he's immediately logged out. 

As per the autodisovery nature of this UI I believe users shouldn't be able to see such buttons, not sure if there's a solution on a framework level but it'll be good to look into such instead of looking into each custom role and logging each button that shouldn't be available to user. 

![readonly](https://user-images.githubusercontent.com/13551960/85721717-4ab9ef00-b6fa-11ea-9a54-a577de576f46.gif)

**Comment by borisstoyanov** [comment]
![Screenshot 2020-06-25 at 15 43 17](https://user-images.githubusercontent.com/13551960/85722144-aedcb300-b6fa-11ea-8d9e-0279e2be2fc7.png)
![Screenshot 2020-06-25 at 15 44 23](https://user-images.githubusercontent.com/13551960/85722234-c0be5600-b6fa-11ea-9e98-9f504c5bc600.png)
View console and get diagnostics data is also available

**Comment by rhtyd** [comment]
@borisstoyanov 
- the console access is not controlled under API discoverery; and this is largely as backend issue than frontend, but we can still decide to show/hide based on access of some API, which API you reckon we should check (something like if user can access API X then show otherwise hide?)
- the get diagnostic is available as your read only admin must have get* APIs enabled.
- the order row bug would then also apply for zones, templates etc. maybe role permissions ordering as well

**Comment by rhtyd** [comment]
With @shwstppr - likely requires the pattern we used in other parts of the code `api in $store.getters.api` to disable the buttons (the order column handled in ListView.vue and also check the role rulepermissions tab for rules ordering)
