### ISSUE TITLE
Build and packaging improvements

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#510]
Hi @utchoang can you explore the following after your current issue, thanks.

1. Explore and optimise build specifically around this npm build warning: (i.e. can we make bundle smaller to load application faster)
```
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/app.93807bba.js (2.55 MiB)
  css/chunk-vendors.ed28034b.css (512 KiB)
  js/chunk-vendors.27bdb886.js (2.55 MiB)
  color.less (266 KiB)
```

2. For both rpm and deb packaging (see https://github.com/apache/cloudstack-primate/tree/master/packaging and packaging.sh) can we ensure that on upgrade it won't overwrite the config.js file

**Comment by utchoang** [comment]
Currently, I have only found a few issues:
1. In node_modules, we use package `@antv/g2`, this package is used in the chart.
=> Ignore package `@antv/g2` because I think Primate doesn't seem to use the chart.

2. Ant design icons are imported entirely including icons not used in Primate
=> Only import component icons to use in Primate. Refer: https://stackoverflow.com/questions/48721290/ant-design-huge-imports

3. In src/locales, JSON files are being imported directly, so its size is very large (> 2 MB)
=> There is still no better way.

![image](https://user-images.githubusercontent.com/13766648/87512222-d5aa5b80-c6a0-11ea-8c47-a16082be12d6.png)

**Comment by utchoang** [comment]
@rhtyd Also can I use `core/lazy_use` instead of `core/use` in main.js? Because to avoid arising unused components.

**Comment by utchoang** [comment]
@rhtyd What do you think about my comment?

**Comment by rhtyd** [comment]
@utchoang I'm on holiday, I'll get back to you next week. Meanwhile you may work with @svenvogel @davidjumani for inputs, thanks.
@davidjumani can you collaborate with @utchoang and advise any bugs, tasks if necessary. Thanks.

**Comment by rhtyd** [comment]
@utchoang I'm okay with removing any dependency such as `@antv/g2` that is not used at all as long as they don't add any regression. The for ant design icons, I think it may be too much effort to find and add icons individually - is there a way to exclude unused icons at build time - otherwise let that be. I think locales is fine, can you look at if we should explore how files are bundled?

**Comment by rhtyd** [comment]
Have a PR, closing this to track on PR.
