### ISSUE TITLE
Consolidated Bug List from Testing/Review

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-primate#528]
List of issues raised by Alex wrt https://github.com/apache/cloudstack-primate/issues/519

- Change or remove (explain?) what "Add new VM" is from VPC tiers tab; (a) allow users to add existing VMs or (b) deploy new VMs on the specific VPC tier, the deployment form does not auto-select the specific VPC tier
- Fix button name in VM deployment form in its network section to "Create New Network"
- Hide the 'create private gateway' button for Users in VPC view (users not allowed to create private gateway)
- Hide SG feature when there are no zones with SG enabled (may be done during API discovery, don't create the SG route if no zones have SG enabled)
- Don't allow users in UI to delete/archive events
- Fix the add and edit users form to show timezone as list of searchable dropdown like in the add account form
- From VRs or systemvms, click on compute offering the URL/path is not added with ?issystem=true, and show an empty resource view
- Check and don't allow domain admins to see VRs tab in guest networks and in VPCs

Usability (optional?):
- Show buttons with labels on resource view when the number of action buttons are very few                                                                                   
- Add resources tab like from zone, but for pod and cluster (listCapacity)
- All icons UI-wide look hanging at the bottom in Firefox but not Chrome (could be AntD bug)
- Whether we should show the reset password button for all VMs, including those not password enabled? (hidden in Primate based on password enabled option)

**Comment by rhtyd** [comment]
With @davidjumani - please check and add in comments if I missed anything

**Comment by davidjumani** [comment]
While in a project view, the account column in the list view / info card shows the project account. It should be changed to project itself.
This is seen in ssh keys, instance groups, private gateways, vpn gateways, and perhaps others too

![Screenshot from 2020-07-11 09-57-13](https://user-images.githubusercontent.com/8244774/87216421-2ea28880-c35d-11ea-87b7-fe7ce064ab57.png)
![Screenshot from 2020-07-11 09-57-24](https://user-images.githubusercontent.com/8244774/87216424-2fd3b580-c35d-11ea-8a8f-96477811fca0.png)

**Comment by davidjumani** [comment]
- Show HA provider only if it is supported. Can perform the listHostHaProvider to check whether the hypervisor is supported 
- Missing capacity fields while creating primary storage
- Contextual help is missing for creating service offerings
- When migrating a vm / systemvm, exclude the current host from the list
- While changing a systemvm service offering, need to fetch system offerings by passing `issystem=true`, `virtualmachineid` and `systemvmtype` to the listServiceOfferings api
- In the event listview, clicking the username redirects to the event not the user
- While listing domains, on refresh, it goes back to the root domain (context is lost)
- Add option to search settings for account / domain
- When editing a role, resource admin is not in the

**Comment by davidjumani** [comment]
@utchoang Could you work on the following :
- Hide SG feature when there are no zones with SG enabled (may be done during API discovery, don't create the SG route if no zones have SG enabled)
- Fix the add and edit users form to show timezone as list of searchable dropdown like in the add account form
- Change or remove (explain?) what "Add new VM" is from VPC tiers tab; (a) allow users to add existing VMs or (b) deploy new VMs on the specific VPC tier, the deployment form does not auto-select the specific VPC tier [preferably the former, to add existing vms]

**Comment by utchoang** [comment]
@davidjumani @rhtyd 
- Hide SG feature when there are no zones with SG enabled (may be done during API discovery, don't create the SG route if no zones have SG enabled)
>> This means that if there is no zone with SG enabled, `networks> security group` will not be displayed?

- Change or remove (explain?) what "Add new VM" is from VPC tiers tab; (a) allow users to add existing VMs or (b) deploy new VMs on the specific VPC tier, the deployment form does not auto-select the specific VPC tier [preferably the former, to add existing vms]
>> I still don't know this requirement very well, can you describe it more clearly?

**Comment by davidjumani** [comment]
> This means that if there is no zone with SG enabled, `networks> security group` will not be displayed?

@utchoang Exactly!

> I still don't know this requirement very well, can you describe it more clearly?
![Screenshot from 2020-07-21 13-52-29](https://user-images.githubusercontent.com/8244774/88030989-945ef380-cb59-11ea-9473-a953a9268582.png)

In the VPC View > Networks > Instances, when 'Add Instance' is selected, preferably open a new component to select a VM from the existing vms. If that would be too time-consuming, just rename it to deploy vm

**Comment by utchoang** [comment]
@davidjumani I got it. Thanks.

**Comment by rhtyd** [comment]
@davidjumani can you strike off anything from the list that got merged from the consolidate bugfix PR

**Comment by davidjumani** [comment]
Fixed from the original list :

Via #552
- ~Change or remove (explain?) what "Add new VM" is from VPC tiers tab; (a) allow users to add existing VMs or (b) deploy new VMs on the specific VPC tier, the deployment form does not auto-select the specific VPC tier~
- ~Hide SG feature when there are no zones with SG enabled (may be done during API discovery, don't create the SG route if no zones have SG enabled)~
- ~Fix the add and edit users form to show timezone as list of searchable dropdown like in the add account form~

Fixed in #539 
- ~Fix button name in VM deployment form in its network section to "Create New Network"~
- ~Hide the 'create private gateway' button for Users in VPC view (users not allowed to create private gateway)~ : Users do not have access to the create gateway API so already covered
- ~Don't allow users in UI to delete/archive events~
- ~From VRs or systemvms, click on compute offering the URL/path is not added with ?issystem=true, and show an empty resource view~
- ~Add resources tab like from zone, but for pod and cluster (listCapacity)~

TODO : 
- Check and don't allow domain admins to see VRs tab in guest networks and in VPCs : But domain admins do have access to listrouters. Perhaps just remove the router-link ?
- Show buttons with labels on resource view when the number of action buttons are very few
- All icons UI-wide look hanging at the bottom in Firefox but not Chrome (could be AntD bug)
- Whether we should show the reset password button for all VMs, including those not password enabled? (hidden in Primate based on password enabled option)

**Comment by davidjumani** [comment]
@rhtyd Can close this. Have created another issue of things todo from this

**Comment by rhtyd** [comment]
okay @davidjumani
