### ISSUE TITLE
[BUG] Creating Basic Type Zone not supported in primate UI ?

### ISSUE THREAD

**Issue by a31amit** [apache/cloudstack-primate#571]
**Describe the bug**

When creating a Zone from UI, older UI gives two options as Basic and Advanced Zone Create, However in Primate UI only Advanced is visible to select. 

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Infrastructure'
3. Click on 'Zones' and then Add Zones. 
4. Only Advanced Type is visible

**Expected behavior**
Option to create Basic Zone Type should also be available here 

**Screenshots**
![cloudstack-zone-primate](https://user-images.githubusercontent.com/6764613/89724698-4fd9b180-d9bb-11ea-97bb-271ad17450b7.JPG)

**Desktop :**
 - OS:  Windows
 - Browser: Chrome / FireFox
 - Version: ACS-4.14 and Primate UI

**Additional context**
Option to create Basic Type Zone is supported in old UI

**Comment by rhtyd** [comment]
@a31amit We've been discussing deprecating basic zone in future release of CloudStack, all features of a basic zone are available with an Advance zone; for example, deploy an Advanced zone with SG or with only shared networks. For newer deployments, we want to promote users to only use Advanced zones (through UI, APIs and old UI will still continue to support deploying basic zone). References:
https://github.com/apache/cloudstack/pull/2720
https://github.com/apache/cloudstack/pull/2748

Due to this in the new UI, Primate, we've not added support for adding a basic zone via the zone deployment wizard, however, any existing basic zone will continue to work with Primate. If there is a reason why it must be supported, please start a discussion thread on the CloudStack dev mailing list.

**Comment by a31amit** [comment]
@rhtyd Thanks for the explaining. I don't have any reason to use BasicZone If I could do the same thing with AdvancedZone. just a thought that may be having the same info in the release or additional deprecation docs would help users more.

**Comment by rhtyd** [comment]
@davidjumani can you put in a line in the doc PR that basic zone deployment is not supported by Primate?

**Comment by davidjumani** [comment]
Added https://github.com/apache/cloudstack-documentation/pull/142/commits/bef0870c1f0c8585a4e202bfd2c08a7453096e2e

**Comment by rhtyd** [comment]
Thanks for addressing limitation in docs @davidjumani I'll close as @a31amit agrees to use Adv zone as long as all the basic zone features are available (which indeed are)
