### ISSUE TITLE
[BUG] During logout, the last "URL" is part of the "logged-out" URL - causing issues...

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#704]
as Admin, go to the UI part that is NOT accessible for i.e. "user" role (global configuration), then log out - you get the URL as above:

http://localhost/#/user/login?redirect=%2Fglobalsetting%3Fname%3Dpublic%26q%3Dpublic%26page%3D1%26pagesize%3D10

Then if you log in as a regular user account, you get 404:

![image](https://user-images.githubusercontent.com/45762285/92928795-e9bfce80-f43f-11ea-8d36-617b1e61eb36.png)

After log out - we should NOT remember the previous position in UI - (expired/logged out or explicitly/manually logged out)

**Comment by andrijapanicsb** [comment]
if someone shares a link like that ( to the i.e. global config page, or to a specific VM/template/etc) - then we should still honour the "redirect=" part of the URL - but initially, do NOT generate that URL after a log out

**Comment by utchoang** [comment]
The problem is that if the user is on a landing page (ex: detail page). After the user logs in again if a be un-remembers URL then will be redirected to the dashboard page. This will cause the user to move some steps to get back to the correct landing page. 
@rhtyd @davidjumani What do you think about this issue?

**Comment by rhtyd** [comment]
We may address in two ways:
(a) I think if a user explicitly logs out then we don't need to remember the last path
(b) if a user logs out due to session timeout (or mgmt server restart) then we should remember the path
What do you think @borisstoyanov @andrijapanicsb @PaulAngus @davidjumani @svenvogel ?

**Comment by andrijapanicsb** [comment]
If that doesn't bring complexity that's OK - otherwise I prefer not to remember the path at all - as the issue of the user having to go again to the same page is very unfrequent (what @utchoang explained), though a nice improvement if possible.

**Comment by davidjumani** [comment]
Think it makes sense to remember the path on session timeout, not on logout

**Comment by PaulAngus** [comment]
I agree with @andrijapanicsb - it's not worth the UI errors that get thrown.

**Comment by rhtyd** [comment]
I think it was like that before but then we got an issue reported here see https://github.com/apache/cloudstack-primate/issues/456 @PaulAngus @andrijapanicsb  cc @borisstoyanov 
Is David's fix to only forget redirect path on explicit logout acceptable, or now we want to revert the fix we did for #456 (that is simply forget path on session/explicit logout)

**Comment by rhtyd** [comment]
@andrijapanicsb cc @PaulAngus please review, test and close. I discussed with Andrija and we're now forgetting the path on explicit logout but not on logout due to session timeout (or mgmt server restart).

**Comment by DaanHoogland** [comment]
complementary to #650 , i will re-test both

**Comment by DaanHoogland** [comment]
works with latest
