### ISSUE TITLE
[BUG] Domain admin cannot edit a domain they created

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#747]
**Describe the bug**
If a domain admin makes a typo in a domain name, they cannot correct themselves.

**To Reproduce**

1. Log in as a Domain Admin
1. create a sub domain in user env
1. try and find a rename/edit button

**Expected behavior**
See the screen shots as find the old UIs functionality.

**Screenshots**
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/2486961/94120968-0c46e400-fe51-11ea-9ca5-d86b4e738b86.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/2486961/94121021-1c5ec380-fe51-11ea-860d-3cb9eae0d3f9.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by utchoang** [comment]
@DaanHoogland @rhtyd cc @svenvogel  On the old UI side, Domain Admin is only allowed to edit resources, not edit domain names. So in the new UI, you can update the resource on the resource tab instead of needing the edit button like the old UI. Thanks.
* Domain Admin
![image](https://user-images.githubusercontent.com/13766648/94225403-0b7c8380-ff1f-11ea-877b-cdd49dec2534.png)

* Admin
![image](https://user-images.githubusercontent.com/13766648/94225453-2e0e9c80-ff1f-11ea-9c77-cf250f1b953a.png)

**Comment by DaanHoogland** [comment]
good explanation @utchoang closing (verified that the API is not available for domain admins which i think is the real bug!)
