### ISSUE TITLE
[BUG] When deploying VM, disk offering for data disks are not all listed

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#803]
**Describe the bug**
When deploying a VM with data disks, the UI will show you just the default offerings instead all. 

All offerings:
![Screenshot 2020-09-30 at 15 01 10](https://user-images.githubusercontent.com/13551960/95825311-56790200-0d39-11eb-97ff-cd1e50b0108c.png)

When deploying template with data disksk
![Screenshot 2020-09-30 at 14 59 23](https://user-images.githubusercontent.com/13551960/95825345-61339700-0d39-11eb-8f8d-06a969ec8d29.png)

Comment from Hari: 
For fixed disk offerings we need to have data disk offerings which are either 5GB and above or custom disk offerings, since the data disk is of 5GB it is looking for suitable disk offerings. The one in the screenshots are less than 5GB

![image-20201012-074246](https://user-images.githubusercontent.com/13551960/95825417-7c9ea200-0d39-11eb-82de-77cf8fe56c80.png)

Even then I see a bug where the listDiskOfferingCmd is properly listing all disk offerings but primate is not showing any custom disk offerings in case of multi disk templates.

**Additional context**

**Comment by utchoang** [comment]
@borisstoyanov @rhtyd cc @svenvogel So does that mean the list disk offering will include data disk offering with value `>= 5 GB` and the custom disk offering?

**Comment by borisstoyanov** [comment]
I think so @utchoang, @andrijapanicsb @nvazquez can you confirm
cc: @davidjumani

**Comment by davidjumani** [comment]
@utchoang It already filters offerings >= 5GB. Need to confirm whehter custom disk offerings are supported for datadisk templates or not @andrijapanicsb

**Comment by andrijapanicsb** [comment]
It's always easy to see how the old UI works - what offerings are listed there.

Afaik, this is multidisk template - where you match offering to a data disk from the template - and only the ones with size >= "volume size from template" are shown.

Not sure abou the custom offerings though - I just checked on old UI - both the stock and the new one (custom offering) are NOT showing.

I think this is OK - since the custom disk offering can be smaller than 5GB (volume size from  the template) - and we don't want to allow that (we also hide fixed disk offerings smaller than 5GB, just checked on the old UI) - 

In theory, this could be done better, as there is a "custom.diskoffering.size.min" global setting - even when setting this one to 6 (6GB) atm we doesnt't show it in that offering list in deployment wizard (theoretically, it should, as we Set the min custom disk size to be BIGGER than the volume-from-template size)

**Comment by davidjumani** [comment]
@andrijapanicsb I think supporting custom disk sizes will require several backend chagnes since right now it isn't supported

**Comment by andrijapanicsb** [comment]
I didn't ask for it - we are now in GA - and ues, backend changes, below is my take on it:

it's not only the UI - it's also the backend - and IF we should support it or not - probably NOT - as we don't have (atm) a way for ACS to validate if the customer wanted to cheat by choosing a smaller custom disk size, than the real volume size (from the template, 5GB in this example, but couild be anything...) - thus tricking the billing (we don't resize or anything - we just assign an offering in the DB, for billing purposes - AFAIK)

Also, starting from 4.15 and onwards, any newly registered template (for VMware, as this bug is related to VMware only) - we are using templates as they are - i.e. NO choosing of offering for each disk, or anything (in background we assign each disk/volume to a custom offering with the same size as the size of the volume) - so absolutely no need to invest any effor here - IMO at least.

**Comment by borisstoyanov** [comment]
I think it'll be good if customer is able to select bigger or smaller offering for the data disks, and it's not just the size but every other option that a custom predefined offering allows you to do (like for example tags to deploy the disk to a specific pool). Should we do it now or now is a separate question, but definitely worths having it. 
--jsut my 2 cents.

**Comment by andrijapanicsb** [comment]
As long as the customer doesn't shoot himself in the foot - I agree - let's leave this for 1.1

**Comment by davidjumani** [comment]
Since custom disk offerings aren't supported yet in the backend, can close this and reopen once support has been added

**Comment by borisstoyanov** [comment]
ok, lets close and reopen when backend support is available
